/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "reacterverless-20210217233139-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d3eh3dzhq4att7.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-2:95647b07-2c70-4a94-abc2-07f136919a65",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_H2DcMFUea",
    "aws_user_pools_web_client_id": "2kg7eka7k0k96nfs9lvfb9jthd",
    "oauth": {}
};


export default awsmobile;
